### ISSUE TITLE
Unable to renew token

### ISSUE THREAD

**Issue by andersfugmann** [dk/Net-MitDK#1]
`mitdk-authenticate` is unable to retrieve a new token from MitID.
When pressing the `NemID` login button, the MitID login page displays: 
`An error has occured. Ref. no. 20231214095004-XXXX`.

**Comment by dk** [comment]
Hi Anders, that's because they removed NemID as an auth method. Now only MitID is available. I updated code, and most importantly, documentation, because in addition to auth steps before, one also needs to lower security (and so far I only figured out how to do that on Chrome). See the "Browser security" part in the docs.

I managed to reauth myself, and if you're going to try that again, you'll also need to get the latest IO::Lambda v1.33 version because v1.32 had a bug.

I'll wait with uploading a new module version, would be interesting if it works for you or not

**Comment by andersfugmann** [comment]
Thanks for making this work - and sorry for the delay in replying. 
It works! but i needed to make a small modification. 
The code matches on `/mitdk` for _the case with private only_, but I think it should match on `/login/mitdk`. At least it works with that change :-) I'll open a PR later today.

Thanks for looking into this.

**Comment by dk** [comment]
thank you, confirming that this works! v0.06 is released
